-- Stores
INSERT INTO stores (name, layout_image_url, layout_image_url_2) VALUES
('St Agnes',    'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/st-agnes.png',      NULL),
('Bath',        'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/bath.png',          NULL),
('Brighton',    'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/brighton.png',      NULL),
('Bristol',     'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/bristol.png',       NULL),
('Cambridge',   'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/cambridge.png',     NULL),
('Cardiff',     'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/cardiff.png',       NULL),
('Edinburgh',   'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/edinburgh.png',     NULL),
('Exeter',      'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/exeter.png',        NULL),
('Falmouth',    'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/falmouth.png',      NULL),
('Hawksfield',  'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/hawksfield.png',    NULL),
('Holt',        'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/holt.png',          NULL),
('London',      'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/london-floor1.png',
                'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/london-floor2.png'),
('Poole',       'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/poole-floor1.png',
                'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/poole-floor2.png'),
('St Ives',     'https://toowjbgtnkggmgczolhm.supabase.co/storage/v1/object/public/store-layouts/st-ives.png',       NULL),
('Southwold',   NULL, NULL),
('Leeds',       NULL, NULL);

-- Fixture Ideals (SS = Spring/Summer, AW = Autumn/Winter)
INSERT INTO fixture_ideals (fixture_name, department, ss_ideal, aw_ideal) VALUES
-- Wall fixtures - Mens
('2000 Wardrobe Rail with FF',  'Mens', 10, 8),
('1500 Wardrobe Rail with FF',  'Mens',  7, 5),
('1501 Wardrobe Rail No FF',    'Mens', 10, 8),
('1400 Wardrobe Rail',          'Mens',  8, 6),
('1200 Wardrobe Rail',          'Mens',  7, 5),
('1000 Wardrobe Rail',          'Mens',  5, 4),
('750 Side Rail',               'Mens',  4, 3),
('750 Front Arm',               'Mens',  2, 1),
('2000 Shelves',                'Mens',  2, 1),
('1500 Shelves',                'Mens',  3, 2),
('1200 Shelves',                'Mens',  3, 2),
('1000 Shelves',                'Mens',  2, 1),
-- Wall fixtures - Womens
('2000 Wardrobe Rail with FF',  'Womens', 10, 8),
('1500 Wardrobe Rail with FF',  'Womens',  7, 5),
('1501 Wardrobe Rail No FF',    'Womens', 10, 8),
('1400 Wardrobe Rail',          'Womens',  8, 6),
('1200 Wardrobe Rail',          'Womens',  7, 5),
('1000 Wardrobe Rail',          'Womens',  5, 4),
('750 Side Rail',               'Womens',  4, 3),
('750 Front Arm',               'Womens',  2, 1),
('2000 Shelves',                'Womens',  2, 1),
('1500 Shelves',                'Womens',  3, 2),
('1200 Shelves',                'Womens',  3, 2),
('1000 Shelves',                'Womens',  2, 1),
-- Floor fixtures - Mens
('750 Shelves',                 'Mens',  1, 1),
('2000 Floor Rail with FF',     'Mens',  9, 7),
('1800 Floor Rail with FF',     'Mens',  9, 7),
('1500 Floor Rail (no FF)',      'Mens', 10, 8),
('1500 Floor Rail (with FF)',    'Mens',  8, 6),
('1100 Floor Rail',             'Mens',  7, 5),
('Table 2000/900',              'Mens',  7, 5),
('Table 2000/700',              'Mens',  4, 3),
('Table 1700/900',              'Mens',  6, 4),
('Table 1700/700',              'Mens',  5, 3),
('Table 1500/900',              'Mens',  5, 3),
('Table 1200/900',              'Mens',  3, 2),
('Table 1500/700',              'Mens',  4, 3),
('2600 Bench',                  'Mens',  6, 4),
('1800 Bench',                  'Mens',  3, 2),
('1200/450 Bench',              'Mens',  2, 2),
('1500 Storage Box / Bench',    'Mens',  3, 2),
('1000 Storage Box / Bench',    'Mens',  2, 2),
('750 Storage Box',             'Mens',  1, 1),
('600 Storage Box',             'Mens',  1, 1),
-- Floor fixtures - Womens
('750 Shelves',                 'Womens',  1, 1),
('2000 Floor Rail with FF',     'Womens',  9, 7),
('1800 Floor Rail with FF',     'Womens',  9, 7),
('1500 Floor Rail (no FF)',      'Womens', 10, 8),
('1500 Floor Rail (with FF)',    'Womens',  8, 6),
('1100 Floor Rail',             'Womens',  7, 5),
('Table 2000/900',              'Womens',  7, 5),
('Table 2000/700',              'Womens',  4, 3),
('Table 1700/900',              'Womens',  6, 4),
('Table 1700/700',              'Womens',  5, 3),
('Table 1500/900',              'Womens',  5, 3),
('Table 1200/900',              'Womens',  3, 2),
('Table 1500/700',              'Womens',  4, 3),
('2600 Bench',                  'Womens',  6, 4),
('1800 Bench',                  'Womens',  3, 2),
('1200/450 Bench',              'Womens',  2, 2),
('1500 Storage Box / Bench',    'Womens',  3, 2),
('1000 Storage Box / Bench',    'Womens',  2, 2),
('750 Storage Box',             'Womens',  1, 1),
('600 Storage Box',             'Womens',  1, 1),
-- Wall fixtures - Cold Water
('2000 Wardrobe Rail with FF',  'Cold Water', 10, 8),
('1500 Wardrobe Rail with FF',  'Cold Water',  7, 5),
('1501 Wardrobe Rail No FF',    'Cold Water', 10, 8),
('1400 Wardrobe Rail',          'Cold Water',  8, 6),
('1200 Wardrobe Rail',          'Cold Water',  7, 5),
('1000 Wardrobe Rail',          'Cold Water',  5, 4),
('750 Side Rail',               'Cold Water',  4, 3),
('750 Front Arm',               'Cold Water',  2, 1),
('2000 Shelves',                'Cold Water',  2, 1),
('1500 Shelves',                'Cold Water',  3, 2),
('1200 Shelves',                'Cold Water',  3, 2),
('1000 Shelves',                'Cold Water',  2, 1),
-- Floor fixtures - Cold Water
('750 Shelves',                 'Cold Water',  1, 1),
('2000 Floor Rail with FF',     'Cold Water',  9, 7),
('1800 Floor Rail with FF',     'Cold Water',  9, 7),
('1500 Floor Rail (no FF)',      'Cold Water', 10, 8),
('1500 Floor Rail (with FF)',    'Cold Water',  8, 6),
('1100 Floor Rail',             'Cold Water',  7, 5),
('Table 2000/900',              'Cold Water',  7, 5),
('Table 2000/700',              'Cold Water',  4, 3),
('Table 1700/900',              'Cold Water',  6, 4),
('Table 1700/700',              'Cold Water',  5, 3),
('Table 1500/900',              'Cold Water',  5, 3),
('Table 1200/900',              'Cold Water',  3, 2),
('Table 1500/700',              'Cold Water',  4, 3),
('2600 Bench',                  'Cold Water',  6, 4),
('1800 Bench',                  'Cold Water',  3, 2),
('1200/450 Bench',              'Cold Water',  2, 2),
('1500 Storage Box / Bench',    'Cold Water',  3, 2),
('1000 Storage Box / Bench',    'Cold Water',  2, 2),
('750 Storage Box',             'Cold Water',  1, 1),
('600 Storage Box',             'Cold Water',  1, 1),
-- Accessories / Third Party fixtures
('1000 Shelf',  'Accessories',  4, 4),
('500 Shelf',   'Accessories',  2, 2),
('Peg',         'Accessories',  1, 2),
('1000 Shelf',  'Third Party',  4, 4),
('500 Shelf',   'Third Party',  2, 2),
('Peg',         'Third Party',  1, 2);
